### ISSUE TITLE
Week4_SentinelSat notebook: Update environments.yml to include ipywidgets

### ISSUE THREAD

**Issue by carolmcquillan** [iamdonovan/egm722#19]
Hi Bob,

I don't like to create issues...but I felt obliged to take the hint! :-) :

**Author: Robert McNabb Date: Sunday, 16 April 2023 11:08:51 o'clock BST Subject: RE: Week 4- SentinelSat- Step 1: TqdmWarning

"Thanks for this! It looks like perhaps ipywidgets needs to be added to environments.yml as a requirement. This seems like a great opportunity for someone to open an issue (https://github.com/iamdonovan/egm722/issues) to remind me to update it moving forward. :)"**

Carol

**Comment by iamdonovan** [comment]
Closed with #31
